model:
  pokingrecon:
    nobjs: 1
    mdepth_loss_on: False
    smooth_loss_on: True
    smooth_loss1_on: False
    smooth_loss2_on: True
    smooth_loss_weight: 0.005
    recon_volume_size: 1.0
    rand_method: 'samask_random'
    optim_pose: False
    frame_ids: [ 4,5,6,7,8,9,10,11,12,17,18,19,20,21,22,33,34,47,48,49 ]
    pose_init: [
      [ [ 0.1588,  0.0674 , 0.089 , -0.0219, -0.0275, -0.1945 ],
        [ 0.1742,  0.0839 , 0.0992, -0.0038,  0.0464, -0.3267 ],
        [ 0.1832,  0.0901 , 0.1106,  0.0114,  0.1291, -0.3799 ],
        [ 0.2187,  0.1165 , 0.1108,  0.0392,  0.1165, -0.6658 ],
        [ 0.2317,  0.1381 , 0.1101,  0.0516,  0.1032, -0.8303 ],
        [ 0.2452,  0.2387 , 0.1026,  0.0692,  0.0594, -1.3903 ],
        [ 0.1949,  0.3754 , 0.0919,  0.0813,  0.0153, -1.9506 ],
        [ 0.1731,  0.4175 , 0.0893,  0.0799,  0.0079, -2.0933 ],
        [ 0.1518,  0.4619 , 0.0883,  0.0303, -0.0122, -2.2334 ],
        [ 0.1536,  0.4588 , 0.0896,  0.0257, -0.0055, -2.2224 ],
        [ 0.1201,  0.5059 , 0.092 ,  0.0361,  0.0117, -2.3953 ],
        [ 0.0743,  0.5573 , 0.0921,  0.0522,  0.0226, -2.585 ],
        [ -0.0107,  0.6249 , 0.0854,  0.0755,  0.0137, -2.8554 ],
        [ -0.1067,  0.6684 , 0.0783,  0.1352,  0.0382, -3.0671 ],
        [ 0.1662, -0.6652 , 0.0687, -0.1988, -0.033 ,  3.0425 ],
        [ 0.1661, -0.664  , 0.0704, -0.1954, -0.0285,  3.0388 ],
        [ 0.1956, -0.6190 , 0.0721, -0.2500,  0.0026,  2.8775 ],
        [ 0.1996, -0.6133 , 0.0717, -0.2468, -0.0020,  2.8577 ],
        [ 0.2195, -0.5927 , 0.0766, -0.2433,  0.0172,  2.7612 ],
        [ 0.2399, -0.5706 , 0.0804, -0.2387,  0.0297,  2.6553 ] ]
    ]
    mdepth_fill: False
    motion_mask_loss: False
    motion_mask_loss_all_area: False
    motion_mask_loss_weight: 0.01
    #    znegfill: True
    static_on: False
    white_bkgd: True
    N_rand: 2048
    chunk: 8192
    val_chunk: 8192
    num_frames: 20
    trim_start: 1
    dynamic_on: True
    use_viewdirs: True
    depth_loss_on: True
    depth_loss_lambda: 1.0
    depth_loss_all: False
    depth_loss_outside_mask: True
    depth_loss_miniter: 0
    depth_loss_func: 'l1'
    sparse_loss: False
    sparse_loss_weight: 0.0001
    align_pose_eval: True
    N_samples: 128
    volsdf:
      use_nerfplusplus: True
      obj_bounding_radius: 3.0
      W_geo_feat: 64
      surface_cfg:
        radius_init: 1.0 # ?
        embed_multires: -1
        W: 128
      radiance_cfg:
        W: 128
datasets:
  train: ("kinectrobot_2022_0801_4_skip2_1to51_trainval_tf1",)
  test: "kinectrobot_2022_0801_4_skip2_1to51_trainval_tf4"
dataset:
  kinectrobot:
    data_scale: 2.5
    clip_far: 2.75
    far: 3.0
    near: 0.0
    keep_only: 2
    keep_only_samask: 2
    remove_bg: True

    keep_frames: [ 4,5,6,7,8,9,10,11,12,17,18,19,20,21,22,33,34,47,48,49 ]
solver:
  batch_size: 20
  max_lr: 0.0005
  pose_lr: 0.001
  lrate_decay: 250000
  lrate_decay_pose: 250000
  num_epochs: 10000
  bias_lr_factor: 1
  weight_decay: 0.0
  weight_decay_bias: 0.0
  save_every: True
  resume: False
  save_freq: 1000
  find_unused_parameters: True
  #  detect_anomaly: True
  dist:
    sampler:
      shuffle: True
input:
  shuffle: False
test:
  do_visualization: True
  visualizer: pokingrecon
  evaluators: [ 'pokingrecon_mask_eval','pokingrecon_pose_eval' ]

dataloader:
  collator: ExtendedBatchCollator
