model:

  pokingrecon:
    nobjs: 1
    vi_shift: 0
    
    mdepth_loss_on: False
    smooth_loss_on: True
    smooth_loss1_on: False
    smooth_loss2_on: True
    smooth_loss_weight: 0.005
    recon_volume_size: 1.0
    rand_method: 'samask_inv0_random'
    
    frame_ids: [ 4,5,6,7,8,9,10,11,12,17,18,19,20,21,22,33,34,47,48,49 ]
    fix_objpose_optim_frame_ids: [ ]
    fix_objpose_optim_frame_ids_all_objs: [ [ 4,5,6,7,8,9,10,11,12,17,18,19,20,21,22,33,34,47,48,49 ] ]
    pose_init: [
      [ [ 0.1588,  0.0674,  0.0890, -0.0219, -0.0275, -0.1945 ],
        [ 0.1760,  0.0860,  0.0985,  0.0011,  0.0361, -0.3376 ],
        [ 0.1858,  0.0947,  0.1102,  0.0202,  0.1144, -0.3933 ],
        [ 0.2225,  0.1227,  0.1117,  0.0349,  0.1099, -0.6850 ],
        [ 0.2379,  0.1436,  0.1125,  0.0388,  0.1108, -0.8462 ],
        [ 0.2528,  0.2463,  0.1116,  0.0544,  0.0909, -1.4223 ],
        [ 0.2028,  0.3831,  0.1073,  0.0610,  0.0667, -1.9879 ],
        [ 0.1816,  0.4266,  0.1048,  0.0361,  0.0547, -2.1400 ],
        [ 0.1598,  0.4734,  0.1045, -0.0163,  0.0376, -2.2974 ],
        [ 0.1607,  0.4711,  0.1075, -0.0244,  0.0440, -2.2902 ],
        [ 0.1250,  0.5212,  0.1105, -0.0171,  0.0572, -2.4765 ],
        [ 0.0768,  0.5749,  0.1129, -0.0087,  0.0648, -2.6824 ],
        [ -0.0109,  0.6450,  0.1130, -0.0001,  0.0701, -2.9578 ],
        [ -0.1524,  0.7223,  0.1068,  0.0176,  0.0572, -3.2957 ],
        [ 0.2096, -0.6065,  0.0876, -0.0270, -0.0290,  2.7485 ],
        [ 0.2123, -0.6041,  0.0872, -0.0239, -0.0288,  2.7386 ],
        [ 0.2618, -0.5347,  0.0880, -0.0314, -0.0214,  2.4245 ],
        [ 0.2655, -0.5295,  0.0869, -0.0310, -0.0226,  2.4008 ],
        [ 0.2802, -0.5095,  0.0880, -0.0356, -0.0183,  2.3016 ],
        [ 0.2953, -0.4885,  0.0895, -0.0346, -0.0161,  2.1938 ], ]
    ]
    mdepth_fill: False
    mdepth_fill_bg: True
    motion_mask_loss: False
    motion_mask_loss_all_area: False
    motion_mask_loss_weight: 0.002
    motion_mask_loss_exp: True
    #    znegfill: True
    static_on: True
    white_bkgd: False
    N_rand: 1024
    chunk: 8192
    #    val_chunk: 8192
    val_chunk: 16384
    netchunk: 131072
    
    
    
    
    num_frames: 20
    trim_start: 1
    dynamic_on: True
    use_viewdirs: True
    depth_loss_on: True
    depth_loss_lambda: 1.0
    depth_loss_all: False
    #    depth_loss_outside_mask: True
    depth_loss_miniter: 0
    depth_loss_func: 'l1'
    sparse_loss: True
    sparse_loss_weight: 0.00001
    sparse_loss_weighted: True
    sparse_loss_decay: -400
    align_pose_eval: True
    N_samples: 192
    volsdf:
      use_nerfplusplus: True
      obj_bounding_radius: 3.0
      W_geo_feat: 64
      surface_cfg:
        radius_init: 1.0 # ?
        embed_multires: -1
        W: 128
      radiance_cfg:
        W: 128
    override_poses_all_objs: [ True ]
    ignore_gripper: True
    eval_mask_gt_id: 2
datasets:
  train: ("kinectrobot_2022_0801_4_skip2_1to51_trainval_tf1",)
  test: "kinectrobot_2022_0801_4_skip2_1to51_trainval_tf4"
dataset:
  kinectrobot:
    gripper_mask_dilate: 7
    data_scale: 2.5
    clip_far: 2.75
    far: 3.0
    near: 0.0
    
    

    keep_frames: [ 4,5,6,7,8,9,10,11,12,17,18,19,20,21,22,33,34,47,48,49 ]
solver:

  batch_size: 20
  max_lr: 0.0005
  pose_lr: 0.001
  lrate_decay: 250000
  lrate_decay_pose: 250000
  num_epochs: 400

  bias_lr_factor: 1
  weight_decay: 0.0
  weight_decay_bias: 0.0
  save_every: True
  resume: True
  load_model: models/cat/joint_stage1/model_epoch_049999.pth
  save_freq: 5
  find_unused_parameters: True
  #  detect_anomaly: True
  dist:
    sampler:
      shuffle: True
input:
  shuffle: False
test:
  do_visualization: True
  visualizer: pokingrecon
  evaluators: [ 'pokingrecon_mask_eval','pokingrecon_pose_eval','pokingrecon_mesh_eval' ]
  save_predictions: True

dataloader:
  collator: ExtendedBatchCollator
tf: 4